"""
tests/test_e2e.py
-----------------
End-to-end test suite for Project Second Thought.

Covers every input type through the full pipeline:
  text    → enrichment → LLM (mocked) → vault write
  url     → web enrichment (mocked) → LLM (mocked) → vault write
  image   → _enrich_image / LLaVA (mocked) → LLM (mocked) → vault write
  audio   → _enrich_audio / Whisper (mocked) → LLM (mocked) → vault write
  share   → /share FastAPI endpoint → pipeline → vault write (via TestClient)

Each test asserts:
  1. The vault file is created in the correct category sub-directory.
  2. The file contains expected Markdown content.
  3. No live Ollama / Whisper / internet call is made (all stubbed).

Run from the repo root:
  pytest omni_capture/tests/test_e2e.py -v
"""
from __future__ import annotations

import base64
import io
import json
import sys
import tempfile
import textwrap
from pathlib import Path
from unittest import mock

import pytest

# Make omni_capture importable when running from repo root.
sys.path.insert(0, str(Path(__file__).parent.parent))

# SRV-01: these four TestClient tests used to set OMNI_GUI_SECRET="" and rely on
# server._require_secret returning early — i.e. they were exercising the
# fail-OPEN path as if it were the product. _require_secret now fails closed, so
# each of them configures a real secret and presents it on every request. Keep
# the header explicit at the call sites (rather than defaulting it on the
# TestClient) so a route that silently stops being authenticated shows up here.
TEST_SECRET = "e2e-test-secret-1234567890"


def _auth_headers() -> dict[str, str]:
    return {"X-Omni-Secret": TEST_SECRET}

# ── Shared fixtures ────────────────────────────────────────────────────────────


@pytest.fixture()
def vault(tmp_path: Path) -> Path:
    """Temporary vault root — each test gets an isolated directory."""
    return tmp_path


def _fake_capture_output(category="Tech_Notes", filename="e2e-test-note"):
    """Return a minimal valid CaptureOutput dict (matches Pydantic model)."""
    from models import CaptureOutput
    return CaptureOutput(
        category=category,
        suggested_filename=filename,
        markdown_content="## E2E test note\n\nThis is generated by the test suite.",
        rationale="Test rationale.",
        key_signals=["test"],
        confidence=0.95,
        requires_new_category=False,
        new_category_name=None,
    )


def _mock_llm(fake_output):
    """Patch run_llm_engine to return a pre-built CaptureOutput."""
    return mock.patch("llm_engine.run_llm_engine", return_value=fake_output)


# ── Helpers ────────────────────────────────────────────────────────────────────


def _written_file(vault: Path, category: str, filename: str) -> Path:
    """Locate the written Markdown file inside the vault."""
    cat_dir = vault / category
    candidates = list(cat_dir.glob(f"{filename}*.md"))
    assert candidates, (
        f"Expected a file matching '{filename}*.md' in {cat_dir}, "
        f"but found: {list(cat_dir.iterdir()) if cat_dir.exists() else '(dir missing)'}"
    )
    return candidates[0]


# ── T1: Plain text input ───────────────────────────────────────────────────────


def test_text_input_writes_vault_file(vault: Path):
    """Plain text travels through the pipeline and lands in the vault."""
    from main import run_pipeline

    fake_out = _fake_capture_output()
    with _mock_llm(fake_out):
        result = run_pipeline(
            text="Python asyncio is awesome for concurrent I/O.",
            vault_root=str(vault),
            dry_run=False,
            notify=False,
        )

    assert result["_written_to"] is not None
    written = Path(result["_written_to"])
    assert written.exists()
    assert "E2E test note" in written.read_text()
    assert written.parent.name == "Tech_Notes"


# ── T2: URL input (mocked web fetch) ─────────────────────────────────────────


def test_url_input_enriches_and_writes(vault: Path):
    """A URL is enriched (web extract mocked) then written to the vault."""
    from main import run_pipeline

    fake_html = b"""
    <html><head><title>Asyncio Guide</title></head>
    <body><p>Learn Python asyncio step by step.</p></body></html>
    """

    fake_resp = mock.MagicMock()
    fake_resp.read.return_value = fake_html
    fake_resp.__enter__ = lambda s: s
    fake_resp.__exit__ = mock.MagicMock(return_value=False)

    fake_out = _fake_capture_output(filename="asyncio-guide")
    with _mock_llm(fake_out), \
         mock.patch("urllib.request.urlopen", return_value=fake_resp):
        result = run_pipeline(
            url="https://realpython.com/async-io-python/",
            vault_root=str(vault),
            dry_run=False,
            notify=False,
        )

    assert result["_written_to"] is not None
    written = Path(result["_written_to"])
    assert written.exists()
    assert written.parent.name == "Tech_Notes"


# ── T3: GitHub URL ────────────────────────────────────────────────────────────


def test_github_url_enriches_via_api(vault: Path):
    """A GitHub repo URL is enriched via the public API (mocked)."""
    from main import run_pipeline

    fake_api_data = json.dumps({
        "full_name": "pallets/flask",
        "description": "The Python micro web framework.",
        "language": "Python",
        "stargazers_count": 67000,
        "topics": ["web", "framework"],
        "license": {"name": "BSD-3-Clause"},
    }).encode()

    fake_resp = mock.MagicMock()
    fake_resp.read.return_value = fake_api_data
    fake_resp.__enter__ = lambda s: s
    fake_resp.__exit__ = mock.MagicMock(return_value=False)

    fake_out = _fake_capture_output(filename="pallets-flask")
    with _mock_llm(fake_out), \
         mock.patch("urllib.request.urlopen", return_value=fake_resp):
        result = run_pipeline(
            url="https://github.com/pallets/flask",
            vault_root=str(vault),
            dry_run=False,
            notify=False,
        )

    assert result["_written_to"] is not None


# ── T4: Image input (LLaVA mocked) ───────────────────────────────────────────


def test_image_input_routes_to_llava(vault: Path):
    """
    A clipboard image is base64-decoded, sent to LLaVA (_enrich_image mocked),
    and the resulting description is written to the vault.
    """
    from main import run_pipeline
    from enrichment_router import _enrich_image
    from models import EnrichedPayload

    # 1×1 transparent PNG (minimal valid image bytes)
    tiny_png = base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
    )

    fake_enriched = EnrichedPayload(
        raw_input="<image>",
        input_type="image",
        enriched_text="A 1×1 transparent pixel. Screenshot of a test.",
        source_metadata={"vision_model": "llava"},
    )

    fake_out = _fake_capture_output(filename="image-capture")
    with _mock_llm(fake_out), \
         mock.patch("enrichment_router._enrich_image", return_value=fake_enriched) as mock_llava:
        # Simulate clipboard image via --text path trick: inject image_bytes directly
        from interceptor import InputPayload
        from enrichment_router import route_and_enrich

        payload = InputPayload(raw="<image_data>", input_type="image_bytes", image_bytes=tiny_png)
        enriched = route_and_enrich(payload)

        assert mock_llava.called, "_enrich_image (LLaVA) should have been called"
        assert enriched.input_type == "image"
        assert "transparent pixel" in enriched.enriched_text

    # Full pipeline with mocked LLaVA via interceptor image path
    with mock.patch("interceptor._try_read_image_from_clipboard", return_value=tiny_png), \
         mock.patch("enrichment_router._enrich_image", return_value=fake_enriched), \
         _mock_llm(fake_out):
        result = run_pipeline(
            vault_root=str(vault),
            dry_run=False,
            notify=False,
        )

    assert result["_written_to"] is not None
    written = Path(result["_written_to"])
    assert written.exists()


# ── T5: Audio input (Whisper mocked) ─────────────────────────────────────────


def test_audio_input_routes_to_whisper(vault: Path, tmp_path: Path):
    """
    An audio file path is passed via --audio; _enrich_audio (Whisper) is mocked
    and the transcript is written to the vault.
    """
    from main import run_pipeline
    from models import EnrichedPayload

    fake_audio = tmp_path / "lecture.wav"
    fake_audio.write_bytes(b"\x00" * 44)  # minimal WAV placeholder

    fake_enriched = EnrichedPayload(
        raw_input=str(fake_audio),
        input_type="audio",
        enriched_text="This is the transcribed audio content from Whisper.",
        source_metadata={"whisper_model": "base", "audio_path": str(fake_audio)},
    )

    fake_out = _fake_capture_output(filename="audio-transcript")
    with mock.patch("enrichment_router._enrich_audio", return_value=fake_enriched) as mock_whisper, \
         _mock_llm(fake_out):
        result = run_pipeline(
            audio=str(fake_audio),
            vault_root=str(vault),
            dry_run=False,
            notify=False,
        )

    mock_whisper.assert_called_once_with(str(fake_audio))
    assert result["_written_to"] is not None
    written = Path(result["_written_to"])
    assert written.exists()


# ── T6: Browser share endpoint (/share via FastAPI TestClient) ────────────────


def test_share_endpoint_url_only(vault: Path):
    """
    POST /share with only a URL (no selection) runs the pipeline and writes
    the vault file.  Uses FastAPI's TestClient; Ollama mocked.
    """
    pytest.importorskip("fastapi", reason="fastapi not installed")
    from fastapi.testclient import TestClient

    # Point config at our temp vault before importing server
    import config as cfg_mod
    cfg_mod._cfg = None
    cfg_mod._DEFAULT_CONFIG_PATH = Path("/nonexistent/config.toml")

    import os
    os.environ["OMNI_VAULT_ROOT"] = str(vault)
    os.environ["OLLAMA_MODEL"] = "llama3.2"
    os.environ["OLLAMA_BASE_URL"] = "http://localhost:11434/v1"
    os.environ["OMNI_GUI_SECRET"] = TEST_SECRET

    fake_html = b"<html><body><p>Async guide.</p></body></html>"
    fake_resp = mock.MagicMock()
    fake_resp.read.return_value = fake_html
    fake_resp.__enter__ = lambda s: s
    fake_resp.__exit__ = mock.MagicMock(return_value=False)

    fake_out = _fake_capture_output(filename="share-test-note")

    import server as srv_mod
    client = TestClient(srv_mod.app, raise_server_exceptions=True)

    with _mock_llm(fake_out), \
         mock.patch("urllib.request.urlopen", return_value=fake_resp), \
         mock.patch("vector_store.retrieve_related", return_value=[]), \
         mock.patch("vector_store.index_note"):
        resp = client.post(
            "/share",
            json={"url": "https://realpython.com/async-io-python/", "title": "Async IO"},
            headers=_auth_headers(),
        )

    assert resp.status_code == 200

    # Parse the SSE stream for a "done" event
    done_data = None
    for line in resp.text.splitlines():
        if line.startswith("data:"):
            try:
                d = json.loads(line[5:])
                if "path" in d:
                    done_data = d
            except Exception:
                pass

    assert done_data is not None, f"No 'done' event in SSE stream:\n{resp.text}"
    assert Path(done_data["path"]).exists()


def test_share_endpoint_with_selection(vault: Path):
    """
    POST /share with a URL + text selection combines them and routes as text,
    not as a URL, so web enrichment is NOT called.
    """
    pytest.importorskip("fastapi", reason="fastapi not installed")
    from fastapi.testclient import TestClient

    import config as cfg_mod
    cfg_mod._cfg = None

    import os
    os.environ["OMNI_VAULT_ROOT"] = str(vault)
    os.environ["OLLAMA_MODEL"] = "llama3.2"
    os.environ["OLLAMA_BASE_URL"] = "http://localhost:11434/v1"
    os.environ["OMNI_GUI_SECRET"] = TEST_SECRET

    fake_out = _fake_capture_output(filename="selection-share-note")

    import server as srv_mod
    client = TestClient(srv_mod.app, raise_server_exceptions=True)

    with _mock_llm(fake_out), \
         mock.patch("vector_store.retrieve_related", return_value=[]), \
         mock.patch("vector_store.index_note"), \
         mock.patch("urllib.request.urlopen") as mock_fetch:
        resp = client.post(
            "/share",
            json={
                "url": "https://example.com/article",
                "title": "Example Article",
                "selection": "The most important paragraph from this page.",
            },
            headers=_auth_headers(),
        )

    # Web fetch should NOT have been called (text path was taken instead)
    mock_fetch.assert_not_called()
    assert resp.status_code == 200


# ── T7: /capture audio_b64 endpoint ──────────────────────────────────────────


def test_capture_audio_b64_endpoint(vault: Path, tmp_path: Path):
    """
    POST /capture with content_type=audio_b64 decodes the base64 audio,
    writes a temp WAV file, calls _enrich_audio (Whisper), then writes vault.
    """
    pytest.importorskip("fastapi", reason="fastapi not installed")
    from fastapi.testclient import TestClient
    from models import EnrichedPayload

    import config as cfg_mod
    cfg_mod._cfg = None

    import os
    os.environ["OMNI_VAULT_ROOT"] = str(vault)
    os.environ["OLLAMA_MODEL"] = "llama3.2"
    os.environ["OLLAMA_BASE_URL"] = "http://localhost:11434/v1"
    os.environ["OMNI_GUI_SECRET"] = TEST_SECRET

    fake_audio_bytes = b"\x00" * 44
    audio_b64 = base64.b64encode(fake_audio_bytes).decode()

    fake_enriched = EnrichedPayload(
        raw_input="<audio>",
        input_type="audio",
        enriched_text="Transcribed: hello world from audio.",
        source_metadata={"whisper_model": "base"},
    )
    fake_out = _fake_capture_output(filename="audio-b64-note")

    import server as srv_mod
    client = TestClient(srv_mod.app, raise_server_exceptions=True)

    with mock.patch("enrichment_router._enrich_audio", return_value=fake_enriched) as mock_whisper, \
         _mock_llm(fake_out), \
         mock.patch("vector_store.retrieve_related", return_value=[]), \
         mock.patch("vector_store.index_note"):
        resp = client.post(
            "/capture",
            json={"content_type": "audio_b64", "content": audio_b64},
            headers=_auth_headers(),
        )

    assert resp.status_code == 200
    mock_whisper.assert_called_once()
    # Confirm temp file was deleted
    called_path = mock_whisper.call_args[0][0]
    assert not Path(called_path).exists(), "Temp audio file should be deleted after transcription"


# ── T8: image_b64 endpoint routes to LLaVA ────────────────────────────────────


def test_capture_image_b64_routes_to_llava(vault: Path):
    """
    POST /capture with content_type=image_b64 must call _enrich_image (LLaVA).
    """
    pytest.importorskip("fastapi", reason="fastapi not installed")
    from fastapi.testclient import TestClient
    from models import EnrichedPayload

    import config as cfg_mod
    cfg_mod._cfg = None

    import os
    os.environ["OMNI_VAULT_ROOT"] = str(vault)
    os.environ["OLLAMA_MODEL"] = "llama3.2"
    os.environ["OLLAMA_BASE_URL"] = "http://localhost:11434/v1"
    os.environ["OMNI_GUI_SECRET"] = TEST_SECRET

    tiny_png = base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
    )
    image_b64 = base64.b64encode(tiny_png).decode()

    fake_enriched = EnrichedPayload(
        raw_input="<image>",
        input_type="image",
        enriched_text="A 1×1 transparent test image.",
        source_metadata={"vision_model": "llava"},
    )
    fake_out = _fake_capture_output(filename="image-b64-note")

    import server as srv_mod
    client = TestClient(srv_mod.app, raise_server_exceptions=True)

    with mock.patch("enrichment_router._enrich_image", return_value=fake_enriched) as mock_llava, \
         _mock_llm(fake_out), \
         mock.patch("vector_store.retrieve_related", return_value=[]), \
         mock.patch("vector_store.index_note"):
        resp = client.post(
            "/capture",
            json={"content_type": "image_b64", "content": image_b64},
            headers=_auth_headers(),
        )

    assert resp.status_code == 200
    mock_llava.assert_called_once()
    _, call_kwargs = mock_llava.call_args
    received_bytes = mock_llava.call_args[0][0]
    assert received_bytes == tiny_png, "LLaVA should receive the decoded image bytes"


# ── T9: Dry-run mode ──────────────────────────────────────────────────────────


def test_dry_run_does_not_write_file(vault: Path):
    """With --dry-run, no vault file is created."""
    from main import run_pipeline

    fake_out = _fake_capture_output()
    with _mock_llm(fake_out):
        result = run_pipeline(
            text="This should not be written to disk.",
            vault_root=str(vault),
            dry_run=True,
            notify=False,
        )

    assert result["_written_to"] is None
    cat_dir = vault / "Tech_Notes"
    assert not cat_dir.exists() or not list(cat_dir.glob("*.md"))


# ── T10: Deduplication prevents double-write ──────────────────────────────────


def test_dedup_prevents_double_write(vault: Path):
    """Running the pipeline twice with identical text should not create a second file."""
    from main import run_pipeline

    text = "Unique content that should only be stored once in the vault."
    # "note" is a filename stopword (see storage_engine._FILENAME_STOPWORDS),
    # so the file actually lands at "dedup-check.md".
    fake_out = _fake_capture_output(filename="dedup-check-note")

    with _mock_llm(fake_out):
        r1 = run_pipeline(text=text, vault_root=str(vault), dry_run=False, notify=False)

    # Second run — same text, should be deduplicated (no second vault write)
    fake_out2 = _fake_capture_output(filename="dedup-check-note")
    with _mock_llm(fake_out2):
        r2 = run_pipeline(text=text, vault_root=str(vault), dry_run=False, notify=False)

    cat_dir = vault / "Tech_Notes"
    md_files = list(cat_dir.glob("dedup-check*.md"))
    assert len(md_files) == 1, (
        f"Deduplication failed — found {len(md_files)} files: {md_files}"
    )


# ── T11: No env-var pollution -- OLLAMA_BASE_URL stays bare ───────────────────
#
# Regression for the root cause of "vision capture silently fails": startup
# config-push code used to append "/v1" to OLLAMA_BASE_URL (for the OpenAI-
# compatible text client) and that polluted value then leaked back into
# cfg.ollama.base_url on the next reload_config() (config.py reads
# OLLAMA_BASE_URL first). Native vision calls (enrichment_router.py) build
# their own URLs via cfg.ollama.base_url + "/api/...", so a "/v1"-polluted
# base_url produced http://localhost:11434/v1/api/tags -> 404 on every image
# capture. cfg.ollama.base_url / OLLAMA_BASE_URL must always stay bare.


def test_run_pipeline_does_not_pollute_ollama_base_url_env(vault: Path):
    """main.py:run_pipeline's startup config push must leave OLLAMA_BASE_URL bare."""
    import os

    from main import run_pipeline
    from config import reload_config

    os.environ["OLLAMA_BASE_URL"] = "http://localhost:11434"

    fake_out = _fake_capture_output()
    with _mock_llm(fake_out):
        run_pipeline(
            text="hello world",
            vault_root=str(vault),
            dry_run=True,
            notify=False,
        )

    assert not os.environ["OLLAMA_BASE_URL"].endswith("/v1"), (
        f"OLLAMA_BASE_URL was polluted with /v1: {os.environ['OLLAMA_BASE_URL']!r}"
    )

    # A subsequent reload_config() must keep cfg.ollama.base_url bare too,
    # since config.py reads OLLAMA_BASE_URL back into cfg.ollama.base_url.
    cfg2 = reload_config()
    assert not cfg2.ollama.base_url.endswith("/v1"), (
        f"cfg.ollama.base_url was polluted with /v1: {cfg2.ollama.base_url!r}"
    )


def test_server_run_pipeline_blocking_does_not_pollute_ollama_base_url_env(vault: Path):
    """server.py's /capture -> _run_pipeline_blocking startup config push must leave OLLAMA_BASE_URL bare."""
    import asyncio
    import os

    import config as cfg_mod
    cfg_mod._cfg = None

    os.environ["OMNI_VAULT_ROOT"] = str(vault)
    os.environ["OLLAMA_BASE_URL"] = "http://localhost:11434"

    import server as srv_mod

    fake_out = _fake_capture_output()
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    q: asyncio.Queue = asyncio.Queue()

    with _mock_llm(fake_out), \
         mock.patch("vector_store.retrieve_related", return_value=[]), \
         mock.patch("vector_store.index_note"):
        srv_mod._run_pipeline_blocking("text", "hello from server pipeline", q, loop)

    assert not os.environ["OLLAMA_BASE_URL"].endswith("/v1"), (
        f"OLLAMA_BASE_URL was polluted with /v1: {os.environ['OLLAMA_BASE_URL']!r}"
    )

    from config import reload_config
    cfg2 = reload_config()
    assert not cfg2.ollama.base_url.endswith("/v1"), (
        f"cfg.ollama.base_url was polluted with /v1: {cfg2.ollama.base_url!r}"
    )
