"""
daily_digest.py
---------------
Generates a daily journal entry summarising today's (or any target date's)
captures from the SQLite index.

Output
------
  <vault_root>/Journal/Daily/YYYY-MMM-DD.md

The note is created or overwritten each run (idempotent), making it safe to
schedule as a cron/Windows Task Scheduler job.

Format
------
  # Daily Digest — 2025-Jun-17

  > 7 captures today across 3 categories

  ## Tech_Notes (4)
  - [[python-asyncio-notes]] — 2025-06-17 09:12  ↗ https://...
  - [[fastapi-dependency-injection]]

  ## CRM (2)
  - [[john-doe-follow-up]]
  - [[acme-intro-call]]

  ## Finance (1)
  - [[expense-june-2025]] — uploaded receipt

  ---
  *Generated by Second Thought daily_digest.py*

CLI
---
  python daily_digest.py                    # digest for today
  python daily_digest.py --date 2025-06-15  # specific date
  python daily_digest.py --dry-run          # print, don't write
"""
from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Optional

from config import get_config
from index_writer import init_db


# ── Helpers ───────────────────────────────────────────────────────────────────

def _format_date_label(d: date) -> str:
    """Return e.g. '2025-Jun-17'."""
    return d.strftime("%Y-%b-%d")


def _format_date_iso(d: date) -> str:
    return d.isoformat()


def _obsidian_link(path: str, filename: str) -> str:
    """Return [[filename]] wikilink."""
    stem = Path(path).stem if path else (filename or "unknown")
    return f"[[{stem}]]"


def _source_fragment(row: dict) -> str:
    url = row.get("source_url") or ""
    if url:
        return f"↗ {url}"
    itype = row.get("input_type") or ""
    if itype and itype != "text":
        return f"_{itype}_"
    return ""


# ── Core ──────────────────────────────────────────────────────────────────────

def build_digest(target_date: date, vault_root: Path) -> str:
    """
    Query SQLite for all captures on *target_date* and return the Markdown
    content of the digest note.
    """
    date_str   = _format_date_iso(target_date)
    label      = _format_date_label(target_date)
    date_next  = (target_date + timedelta(days=1)).isoformat()

    conn   = init_db(vault_root)
    cursor = conn.cursor()
    rows   = cursor.execute(
        """
        SELECT category, path, filename, source_url, input_type, timestamp, confidence
        FROM captures
        WHERE timestamp >= ? AND timestamp < ?
        ORDER BY category, timestamp
        """,
        (date_str, date_next),
    ).fetchall()
    conn.close()

    rows = [dict(r) for r in rows]
    total = len(rows)

    if not rows:
        return (
            f"# Daily Digest — {label}\n\n"
            f"> No captures recorded on this day.\n\n"
            f"---\n*Generated by Second Thought daily_digest.py*\n"
        )

    # Group by category
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_cat[r["category"]].append(r)

    cat_count_str = ", ".join(
        f"{len(v)} {k}" for k, v in sorted(by_cat.items(), key=lambda x: -len(x[1]))
    )

    lines: list[str] = [
        f"# Daily Digest — {label}",
        "",
        f"> {total} capture{'s' if total != 1 else ''} today — {cat_count_str}",
        "",
    ]

    for cat in sorted(by_cat.keys()):
        items = by_cat[cat]
        lines.append(f"## {cat} ({len(items)})")
        lines.append("")
        for r in items:
            link = _obsidian_link(r["path"], r.get("filename", ""))
            ts   = (r.get("timestamp") or "")[:16].replace("T", " ")
            src  = _source_fragment(r)
            conf = r.get("confidence")
            conf_str = f" `{round(conf*100)}%`" if conf and conf < 0.85 else ""

            parts = [f"- {link}"]
            if ts:
                parts.append(f"— {ts}")
            if src:
                parts.append(src)
            if conf_str:
                parts.append(conf_str)
            lines.append(" ".join(parts))
        lines.append("")

    lines += [
        "---",
        "*Generated by Second Thought daily_digest.py*",
        "",
    ]
    return "\n".join(lines)


def write_digest(target_date: date, vault_root: Path) -> Path:
    """
    Write (or overwrite) the daily digest note and return its Path.
    Creates the Journal/Daily/ directory if needed.
    """
    content   = build_digest(target_date, vault_root)
    label     = _format_date_label(target_date)
    dest_dir  = vault_root / "Journal" / "Daily"
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest_path = dest_dir / f"{label}.md"
    dest_path.write_text(content, encoding="utf-8")
    return dest_path


# ── CLI / schedule entry point ────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> None:
    import argparse

    p = argparse.ArgumentParser(description="Generate a daily journal digest from Second Thought.")
    p.add_argument(
        "--date",
        default=None,
        help="Target date in YYYY-MM-DD format (default: today).",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the digest to stdout without writing to disk.",
    )
    args = p.parse_args(argv)

    cfg = get_config()

    if args.date:
        try:
            target = date.fromisoformat(args.date)
        except ValueError:
            print(f"[DailyDigest] Invalid date '{args.date}'. Use YYYY-MM-DD.", file=sys.stderr)
            sys.exit(1)
    else:
        target = date.today()

    if args.dry_run:
        print(build_digest(target, cfg.vault.root))
    else:
        path = write_digest(target, cfg.vault.root)
        print(f"[DailyDigest] Wrote digest → {path}")


if __name__ == "__main__":
    main()
