/**
 * tauri.ts - thin wrapper around Tauri `invoke` for app-level commands.
 */

import { invoke } from "@tauri-apps/api/core";
import { logger, LogLevel } from "./logger";

let cachedSecret: string | null = null;

/**
 * Returns the GUI secret generated by Rust at startup, caching the resolved
 * value (not the in-flight promise) so a transient failure -- e.g. running
 * in plain `vite dev` outside Tauri -- doesn't wedge every future call.
 */
export async function getGuiSecret(): Promise<string> {
  if (cachedSecret !== null) return cachedSecret;
  try {
    const secret = await invoke<string>("get_gui_secret");
    cachedSecret = secret;
    logger.debug("tauri", "GUI secret resolved", { present: secret.length > 0 });
    return secret;
  } catch (err) {
    // Not running inside Tauri (browser dev) or the command isn't ready yet.
    // Fall back to no secret so dev against a no-secret server still works.
    logger.warn("tauri", "get_gui_secret failed — falling back to empty secret", err);
    return "";
  }
}

export async function setHotkey(hotkey: string): Promise<void> {
  logger.info("tauri", "set_hotkey", { hotkey });
  try {
    await invoke("set_hotkey", { hotkey });
  } catch (err) {
    logger.error("tauri", "set_hotkey failed", err);
    throw err;
  }
}

/**
 * Changes the log level at runtime (no rebuild) — updates the frontend
 * logger immediately (persisted in localStorage) and best-effort syncs the
 * Rust side so backend-origin log_line calls are filtered the same way.
 */
export async function setLogLevel(level: LogLevel): Promise<void> {
  logger.setLevel(level);
  try {
    await invoke("set_log_level", { level });
  } catch (err) {
    logger.warn("tauri", "set_log_level (rust) failed — frontend level still applied", err);
  }
}
