/**
 * tauri.ts - thin wrapper around Tauri `invoke` for app-level commands.
 */

import { invoke } from "@tauri-apps/api/core";
import { revealItemInDir } from "@tauri-apps/plugin-opener";
import { logger, LogLevel } from "./logger";
import { logicalToPhysicalRect } from "./monitor";

let cachedSecret: string | null = null;

/**
 * Returns the GUI secret generated by Rust at startup, caching the resolved
 * value (not the in-flight promise) so a transient failure -- e.g. running
 * in plain `vite dev` outside Tauri -- doesn't wedge every future call.
 */
export async function getGuiSecret(): Promise<string> {
  if (cachedSecret !== null) return cachedSecret;
  try {
    const secret = await invoke<string>("get_gui_secret");
    cachedSecret = secret;
    logger.debug("tauri", "GUI secret resolved", { present: secret.length > 0 });
    return secret;
  } catch (err) {
    // Not running inside Tauri (browser dev) or the command isn't ready yet.
    // Fall back to no secret so dev against a no-secret server still works.
    logger.warn("tauri", "get_gui_secret failed — falling back to empty secret", err);
    return "";
  }
}

export async function setHotkey(hotkey: string): Promise<void> {
  logger.info("tauri", "set_hotkey", { hotkey });
  try {
    await invoke("set_hotkey", { hotkey });
  } catch (err) {
    logger.error("tauri", "set_hotkey failed", err);
    throw err;
  }
}

/**
 * Changes the log level at runtime (no rebuild) — updates the frontend
 * logger immediately (persisted in localStorage) and best-effort syncs the
 * Rust side so backend-origin log_line calls are filtered the same way.
 */
export async function setLogLevel(level: LogLevel): Promise<void> {
  logger.setLevel(level);
  try {
    await invoke("set_log_level", { level });
  } catch (err) {
    logger.warn("tauri", "set_log_level (rust) failed — frontend level still applied", err);
  }
}

/** Reveal the current crash/diagnostics log file in the OS file manager, so the user can
 *  attach it to a bug report (the export half of gate pt 6 — capture + rotation already ship
 *  via logger.ts → Rust append_log). Path comes from the Rust `log_file_path` command; the
 *  logs/ dir alongside it also holds the rotated siblings. Best-effort: throws are surfaced to
 *  the caller so the UI can show a failure, but a no-op outside Tauri just logs and returns. */
export async function revealLogFile(): Promise<void> {
  try {
    const path = await invoke<string>("log_file_path");
    await revealItemInDir(path);
  } catch (err) {
    logger.warn("tauri", "revealLogFile failed", err);
    throw err;
  }
}

/** Toggle WS_EX_NOACTIVATE on the *calling* window's HWND (Tauri resolves
 *  the `window` command argument from whichever webview invoked it) so
 *  clicking it never steals foreground focus from another app
 *  (for_sonnet.md). Best-effort: no-op outside Tauri (browser dev). */
export async function setWindowNoactivate(enabled: boolean): Promise<void> {
  try {
    await invoke("set_window_noactivate", { enabled });
  } catch (err) {
    logger.warn("tauri", "set_window_noactivate failed", err);
  }
}

/** Arm the global click-away mouse hook, hit-testing against `windowLabel`'s
 *  HWND. Call only while a menu is open — disarm on every close path. */
export async function armMenuClickAway(windowLabel: string): Promise<void> {
  try {
    await invoke("arm_menu_click_away", { windowLabel });
  } catch (err) {
    logger.warn("tauri", "arm_menu_click_away failed", err);
  }
}

export async function disarmMenuClickAway(): Promise<void> {
  try {
    await invoke("disarm_menu_click_away");
  } catch (err) {
    logger.warn("tauri", "disarm_menu_click_away failed", err);
  }
}

/** Atomic move+resize via Win32 `SetWindowPos` (Windows only — the Rust
 *  command is behind `#[cfg(windows)]`). Args are *logical* px + the
 *  window's current `scaleFactor()`; conversion to physical px happens here,
 *  the one sanctioned physical-coordinate path (mirrors `monitor.ts`).
 *  Throws on failure (missing command on non-Windows, no Tauri context) so
 *  callers can fall back to the two-call `setWindowGeometryInstant`. */
export async function setWindowBoundsAtomic(
  pos: { x: number; y: number },
  size: { w: number; h: number },
  scale: number,
): Promise<void> {
  const { x, y, w, h } = logicalToPhysicalRect(pos, size, scale);
  await invoke("set_window_bounds", { x, y, w, h });
}

export type PairingInfo = {
  enabled: boolean;
  host: string | null;
  port: number;
  secret: string;
  key: string;
  lan_ip?: string;
};

export async function getPairingInfo(): Promise<PairingInfo> {
  return invoke<PairingInfo>("get_pairing_info");
}

export async function setPairingEnabled(enabled: boolean): Promise<PairingInfo> {
  return invoke<PairingInfo>("set_pairing_enabled", { enabled });
}

export async function rotateSecret(): Promise<string> {
  return invoke<string>("rotate_secret");
}

/** QR payload — MUST match phone/src/lib/pairing.ts parsePairingPayload (contract §9/§11.4,
 *  PairingPayload v3). LAN file-sync accelerator, not Tailscale chat: host is the desktop's LAN
 *  IPv4, key is the base64 NaCl secretbox key. `device` is the desktop's stable device-id (from
 *  GET /lan/device-id) — the anchor mDNS/hub-hint discovery matches against (§11.8). The phone
 *  rejects v1/v2, so `device` is required. */
export function buildPairingPayload(info: PairingInfo, device: string): string {
  const host = info.lan_ip ?? info.host ?? "";
  return JSON.stringify({ v: 3, host, port: info.port, key: info.key, secret: info.secret, device });
}
